Laborationer/Lab3.2/Models/Grade.cs
namespace Lab3._2.Models
{
    public class Grade
    {
        public int GradeId { get; set; }
        public string CourseName { get; set; }
        public string CourseGrade { get; set; }
        public int StudentId { get; set; }
    }
}

Laborationer/Lab3.2/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab3._2.Models
{
    public class Student
    {
        public int StudentId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string PersonNumber { get; set; }
        public string Address { get; set; }
        public List<Grade> Grades { get; set; } //virtual används för att EF ska kunna kopplas till den 
    }
}

Laborationer/Lab3.2/Controllers/GradeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab3._2.Models;

namespace Lab3._2.Controllers
{
    public class GradeController : Controller
    {
        public PartialViewResult _ListForStudent(int studentId)
        {
            List<Grade> grades = ((Student)Session["Student"]).Grades;
            return PartialView(grades);
        }

        public PartialViewResult _Add(int studentId)
        {
            return PartialView(new Grade() {StudentId = studentId});
        }

        [HttpPost]
        public ActionResult _Add(Grade model)
        {
            ((Student)Session["Student"]).Grades.Add(model);
            return RedirectToAction(actionName: "_ListForStudent", routeValues: new { studentId = model.StudentId });
        }

    }
}

Laborationer/Lab3.2/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab3._2.Models;

namespace Lab3._2.Controllers
{
    public class StudentController : Controller
    {
        public ActionResult Details()
        {
            Student student = new Student()
            {
                StudentId = 1,
                Name = "Ivan",
                LastName = "Prgomet",
                PersonNumber = "920620-6717",
                Address = "Oscarsgatan 4",
                Grades = new List<Grade>
                {
                    new Grade {GradeId = 1, CourseName = "MVC", CourseGrade = "MVG"},
                    new Grade {GradeId = 12, CourseName = "HTML5", CourseGrade = "VG"}
                }
            };
            Session["Student"] = student;
            return View(student);
        }
    }
}

Laborationer/Lab3.2/Views/Grade/_Add.cshtml
@model Lab3._2.Models.Grade


@using (Ajax.BeginForm("_Add", "Grade", new AjaxOptions {UpdateTargetId = "gradeContainer"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Grade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.StudentId)
        <div class="form-group">
            @Html.LabelFor(model => model.CourseGrade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseGrade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseGrade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Laborationer/Lab3.2/Views/Grade/_ListForStudent.cshtml
@model List<Lab3._2.Models.Grade>


<table class="table">
    <tr>
        <th>
            Course Name
        </th>
        <th>
            Grade
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CourseName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CourseGrade)
        </td>
    </tr>
}

</table>

Laborationer/Lab3.2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
</body>
</html>

Laborationer/Lab3.2/Views/Student/Details.cshtml
@model Lab3._2.Models.Student

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Student</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>
</div>
<div id="gradeContainer">
    @Html.Action("_ListForStudent", "Grade", new {studentId = Model.StudentId})
</div>
<div>
    @Html.Action("_Add", "Grade", new { studentId = Model.StudentId })
</div>